/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pck;

import java.io.File;
import java.io.IOException;
import java.nio.file.DirectoryIteratorException;
import java.nio.file.DirectoryStream;
import java.nio.file.FileStore;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 *
 * @author laxmi
 */
public class drive extends javax.swing.JFrame {

    /**
     * Creates new form drive
     */
    public drive() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(219, 177, 82));
        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(19, 50, 88));
        jButton1.setText("Drive Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 60));

        jTextArea1.setBackground(new java.awt.Color(200, 216, 211));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(44, 63, 73));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 680, 240));

        jButton2.setBackground(new java.awt.Color(219, 177, 82));
        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(19, 50, 88));
        jButton2.setText("List  Hidden or non Hidden Directories");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 340, 60));

        jTextField1.setText(" ");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 190, 40));

        jLabel2.setBackground(new java.awt.Color(220, 178, 86));
        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setText("Enter the Path :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 160, 30));

        jButton3.setBackground(new java.awt.Color(219, 177, 82));
        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(19, 50, 88));
        jButton3.setText("Display all the files and folder in any drive");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 270, 60));

        jButton4.setBackground(new java.awt.Color(219, 177, 82));
        jButton4.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(19, 50, 88));
        jButton4.setText("File serch by extension");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 230, 60));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 130, 40));

        jLabel3.setBackground(new java.awt.Color(220, 178, 86));
        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setText("Enter the extension :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 190, 30));

        jLabel1.setBackground(new java.awt.Color(169, 215, 134));
        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setText("DRIVE  Management");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 290, 70));

        jButton6.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(209, 62, 62));
        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
      long K = 1024;  
      jTextArea1.setText(" ");
    jTextArea1.append( "Filesystem   "+ "      kbytes   "+ "    used    " + "  avail   ");
       
            FileSystem fs = FileSystems.getDefault();            
            for (FileStore store: fs.getFileStores()) {                
                try{
        long total = store.getTotalSpace() / K;
        long used = (store.getTotalSpace() - store.getUnallocatedSpace()) / K;
        long avail = store.getUsableSpace() / K;
        String s = store.toString();
        if (s.length() > 20) {
            jTextArea1.append("\n"+s);
            s = "";
            jTextArea1.append("   "+ s + "   "+total+"    " + used +"       "+ avail+" \n");            
        }}catch(Exception e){
            jTextArea1.append(e.toString());
        }
            }
    
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                jTextArea1.setText(" ");
        
        String str = jTextField1.getText().trim();
        
        if(str.length()==0){
            str="/home";
        }
	File f = new File(str); // current directory
        

		File[] files = f.listFiles();
		for (File file : files) {
			if (file.isDirectory()) {
				jTextArea1.append("Directory:");
			} else {
				jTextArea1.append("     File:");
			}
                        try{
			jTextArea1.append(file.getCanonicalPath()+"\n");
                        }catch(Exception e)
                        {
                            jTextArea1.append(e.toString());
                        }
		}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
jTextArea1.setText(" ");        
        String str = jTextField1.getText().trim();
        if(str.length()==0){
           str ="/home/laxmi";
        } 
        else {
            str = jTextField1.getText().trim();
        }
         File[] faFiles = new File(str).listFiles();
  for(File file: faFiles){
    if(file.getName().matches("^(.*?)")){
            jTextArea1.append("\n"+file.getAbsolutePath()+" ");
    }
  }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                Path dir;
       String searchstr = jTextField2.getText().trim();
       if(searchstr.length()==0){
        searchstr ="*.*{txt,jar,mkv,class}";
       }
       else {
           searchstr ="*"+jTextField2.getText().trim();
       }
              String st = jTextField1.getText().trim();
        jTextArea1.setText(" ");
        if(st.length()==0){
         dir = Paths.get("/home/laxmi");
        }     
        else{
        dir= Paths.get(st);
        }
try (DirectoryStream<Path> stream =
     Files.newDirectoryStream(dir, searchstr.trim())) {
    jTextArea1.append("\n"+"listing files java,class,jar,mkv that are in the dir path"+dir);
    for (Path entry: stream) {
        jTextArea1.append("\n"+entry.getFileName().toString());
    }
} catch (IOException x) {
    // IOException can never be thrown by the iteration.
    // In this snippet, it can // only be thrown by newDirectoryStream.
    jTextArea1.append("\n"+x.toString());
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
              new drive().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
