/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package myy.prj;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;

/**
 *
 * @author hiddenprivacy
 */
public class frame4 extends javax.swing.JFrame {
public String s9;
public String s10;
public  String s11;
public String s12;
    /**
     * Creates new form frame4
     */
    public frame4() {
        initComponents();
         Toolkit tk =Toolkit.getDefaultToolkit();
        Dimension scr = tk.getScreenSize();
        int h =scr.height;
        int w=scr.width;
        setSize(w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathtxt1 = new javax.swing.JTextField();
        pathtxt2 = new javax.swing.JTextField();
        pathtxt3 = new javax.swing.JTextField();
        pathtxt4 = new javax.swing.JTextField();
        data1 = new javax.swing.JTextField();
        data2 = new javax.swing.JTextField();
        data3 = new javax.swing.JTextField();
        data4 = new javax.swing.JTextField();
        fvtxt1 = new javax.swing.JTextField();
        fvtxt2 = new javax.swing.JTextField();
        fvtxt3 = new javax.swing.JTextField();
        fvtxt4 = new javax.swing.JTextField();
        prttxt2 = new javax.swing.JTextField();
        prttxt3 = new javax.swing.JTextField();
        prttxt4 = new javax.swing.JTextField();
        prttxt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        genbin1 = new javax.swing.JTextField();
        genbin2 = new javax.swing.JTextField();
        genbin3 = new javax.swing.JTextField();
        genbin4 = new javax.swing.JTextField();
        genbintxt8 = new javax.swing.JTextField();
        genbintxt7 = new javax.swing.JTextField();
        genbintxt6 = new javax.swing.JTextField();
        genbintxt5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        binsptxt1 = new javax.swing.JTextField();
        binsptxt2 = new javax.swing.JTextField();
        binsptxt3 = new javax.swing.JTextField();
        binsptxt4 = new javax.swing.JTextField();
        binsptxt7 = new javax.swing.JTextField();
        binsptxt8 = new javax.swing.JTextField();
        binsptxt6 = new javax.swing.JTextField();
        binsptxt5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        crrtxt1 = new javax.swing.JTextField();
        crrtxt2 = new javax.swing.JTextField();
        crrtxt3 = new javax.swing.JTextField();
        crrtxt4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        muttxt1 = new javax.swing.JTextField();
        muttxt2 = new javax.swing.JTextField();
        muttxt3 = new javax.swing.JTextField();
        muttxt4 = new javax.swing.JTextField();
        dectxt4 = new javax.swing.JTextField();
        dectxt3 = new javax.swing.JTextField();
        dectxt2 = new javax.swing.JTextField();
        dectxt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pathtxt1.setText(" ");
        getContentPane().add(pathtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 100, -1));

        pathtxt2.setText(" ");
        getContentPane().add(pathtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, -1));

        pathtxt3.setText(" ");
        getContentPane().add(pathtxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, -1));

        pathtxt4.setText(" ");
        getContentPane().add(pathtxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 100, -1));

        data1.setText(" ");
        getContentPane().add(data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, -1));

        data2.setText(" ");
        getContentPane().add(data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, -1));

        data3.setText(" ");
        getContentPane().add(data3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 100, -1));

        data4.setText(" ");
        getContentPane().add(data4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, -1));

        fvtxt1.setText(" ");
        getContentPane().add(fvtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 100, -1));

        fvtxt2.setText(" ");
        getContentPane().add(fvtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 100, -1));

        fvtxt3.setText(" ");
        getContentPane().add(fvtxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 100, -1));

        fvtxt4.setText(" ");
        getContentPane().add(fvtxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 100, -1));

        prttxt2.setText(" ");
        getContentPane().add(prttxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 100, -1));

        prttxt3.setText(" ");
        getContentPane().add(prttxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 100, -1));

        prttxt4.setText(" ");
        getContentPane().add(prttxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 100, -1));

        prttxt1.setText(" ");
        getContentPane().add(prttxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 100, -1));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, 30));

        genbin1.setText(" ");
        getContentPane().add(genbin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 130, -1));

        genbin2.setText(" ");
        getContentPane().add(genbin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 130, -1));

        genbin3.setText(" ");
        getContentPane().add(genbin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 130, -1));

        genbin4.setText(" ");
        getContentPane().add(genbin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 130, -1));

        genbintxt8.setText(" ");
        getContentPane().add(genbintxt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 180, -1));

        genbintxt7.setText(" ");
        getContentPane().add(genbintxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 180, -1));

        genbintxt6.setText(" ");
        getContentPane().add(genbintxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 180, -1));

        genbintxt5.setText(" ");
        getContentPane().add(genbintxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 180, -1));

        jButton2.setText("Binary generator");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 220, 40));

        binsptxt1.setText(" ");
        getContentPane().add(binsptxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, -1));

        binsptxt2.setText(" ");
        getContentPane().add(binsptxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, -1));

        binsptxt3.setText(" ");
        getContentPane().add(binsptxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 130, -1));

        binsptxt4.setText(" ");
        getContentPane().add(binsptxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 130, -1));

        binsptxt7.setText(" ");
        getContentPane().add(binsptxt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 180, -1));

        binsptxt8.setText(" ");
        getContentPane().add(binsptxt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 180, -1));

        binsptxt6.setText(" ");
        getContentPane().add(binsptxt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 180, -1));

        binsptxt5.setText(" ");
        getContentPane().add(binsptxt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, -1));

        jButton3.setText("Generator at k=6");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 140, 40));

        crrtxt1.setText(" ");
        getContentPane().add(crrtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 280, -1));

        crrtxt2.setText(" ");
        getContentPane().add(crrtxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 280, -1));

        crrtxt3.setText(" ");
        getContentPane().add(crrtxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 280, -1));

        crrtxt4.setText(" ");
        getContentPane().add(crrtxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 280, -1));

        jButton4.setText("Cross Over");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 120, 30));

        muttxt1.setText(" ");
        getContentPane().add(muttxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 130, -1));

        muttxt2.setText(" ");
        getContentPane().add(muttxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 130, -1));

        muttxt3.setText(" ");
        getContentPane().add(muttxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 130, -1));

        muttxt4.setText(" ");
        getContentPane().add(muttxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 130, -1));

        dectxt4.setText(" ");
        getContentPane().add(dectxt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 180, -1));

        dectxt3.setText(" ");
        getContentPane().add(dectxt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 180, -1));

        dectxt2.setText(" ");
        getContentPane().add(dectxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 180, -1));

        dectxt1.setText(" ");
        getContentPane().add(dectxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 180, -1));

        jLabel1.setText("4.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel2.setText("3.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setText("2.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setText("1.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel5.setText("BINARY VALUES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 120, 30));

        jLabel6.setText("S.N");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel7.setText("Data");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel8.setText("Edges");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 50, -1));

        jLabel9.setText("Fitness Value");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel10.setText("Priority");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jLabel13.setText("BINARY AT K=6");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, 40));

        jLabel15.setText("Mutation ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 130, 30));

        jLabel12.setText("DECIMAL VALUES");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 230, 130, 40));

        jLabel14.setText("Cross Over At k=6");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 130, 30));

        jButton5.setText("MUTATION");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 140, 30));

        jButton6.setText("DECIMAL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 120, 30));

        jButton7.setText("Controlflow graph ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 220, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        {
        {
        data1.setText(s9);
        data2.setText(s10);
        data3.setText(s11);
        data4.setText(s12);
             float[] arr =new float[4];
                  float[] cpyarr =new float[4];
                  float[] narr =new float[4];
         arr[0] =Float.parseFloat(fvtxt1.getText().trim());
              arr[1] =Float.parseFloat(fvtxt2.getText().trim());
              arr[2] =Float.parseFloat(fvtxt3.getText().trim());
              arr[3] =Float.parseFloat(fvtxt4.getText().trim());
              for(int i=0;i<4;i++){
                    cpyarr[i] = arr[i];
              }
              
          Arrays.sort(arr);
          float narry[];
            narry = new float[4];
         narry[0] =arr[3];
         narr[1]=arr[2];
         narr[2]=arr[1];
         narr[3]=arr[0];
          //narry = new int[4];
          arr[0]=narry[0];
        arr[1]= narr[1];
        arr[2]= narr[2];
        arr[3]= narr[3];
 for(int i=0;i<4;i++)
                  {
                   for(int j=0;j<4;j++){
                  if(arr[j]==cpyarr[i]){       
                   narr[i]=j;
                  
                  }
                   }
    }
prttxt1.setText(String.valueOf((narr[0])));
 prttxt2.setText(String.valueOf(narr[1]));
 prttxt3.setText(String.valueOf(narr[2]));
 prttxt4.setText(String.valueOf(narr[3]));
        }
 // copy the value in the second table
            String[] starr;
       starr = new String[4];
      int val1 = Integer.parseInt(prttxt1.getText().substring(0,1));
       
       starr[val1]=data1.getText().trim();
       val1 =Integer.parseInt(prttxt2.getText().substring(0,1));
       starr[val1]=data2.getText().trim();
       val1 =Integer.parseInt(prttxt3.getText().substring(0,1));
       starr[val1]=data3.getText().trim();
        val1 =Integer.parseInt(prttxt4.getText().substring(0,1));
       starr[val1]=data4.getText().trim();
     genbin1.setText(starr[0].trim());       
     genbin2.setText(starr[1].trim());       
     genbin3.setText(starr[2].trim());       
     genbin4.setText(starr[3].trim()); 
    
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
               String line = genbin1.getText();{
         String[] tokens = line.split(",(?=([^\"]*\"[^\"]*\")*[^\"]*$)");
         String dataa1 =(tokens[0].toString().trim());
           String dataa2 = (tokens[1].toString().trim());
           String dataa3 = (tokens[2].toString().trim());
           int binry = Integer.parseInt(dataa1);
        String xyz= Integer.toBinaryString(binry);
        StringBuffer temp1 = new StringBuffer(xyz);
  
            int counter =temp1.length();
            while(counter<4){
            char chr ='0';
            temp1.insert(0,chr);
            
            counter++;
            }
            String res=  temp1.toString().trim();
            
           int binr = Integer.parseInt(dataa2);         
        String xy= Integer.toBinaryString(binr);
        StringBuffer temp2 = new StringBuffer(xy);    
        int counter2 =temp2.length();
            while(counter2<4){
            char chr ='0';
            temp2.insert(0,chr);
            
            counter2++;
            }
String str= temp2.toString().trim();
         String res1 = res.concat(str);
       
            
        int bin3 = Integer.parseInt(dataa3);
        String xyy= Integer.toBinaryString(bin3);
         StringBuffer temp3 = new StringBuffer(xyy);    
        int counter3 =temp3.length();
            while(counter3<4){
            char chr ='0';
            temp3.insert(0,chr);
            
            counter3++;
            }
            String str2= temp3.toString().trim();
            String res2 =res1.concat(str2) ;
        String finres =res2.toString().trim();
        genbintxt5.setText(finres);
     
    }
            // Second text box value read
            String line2 = genbin2.getText();{
           String[] tokens = line2.split(",(?=([^\"]*\"[^\"]*\")*[^\"]*$)");
               String dataa1 =(tokens[0].toString().trim());
           String dataa2 = (tokens[1].toString().trim());
           String dataa3 = (tokens[2].toString().trim());
           int binry = Integer.parseInt(dataa1);
        String xyz= Integer.toBinaryString(binry);
        StringBuffer temp1 = new StringBuffer(xyz);
  
            int counter =temp1.length();
            while(counter<4){
            char chr ='0';
            temp1.insert(0,chr);
            
            counter++;
            }
            String res=  temp1.toString().trim();
           int binr = Integer.parseInt(dataa2);         
        String xy= Integer.toBinaryString(binr);
        StringBuffer temp2 = new StringBuffer(xy);    
        int counter2 =temp2.length();
            while(counter2<4){
            char chr ='0';
            temp2.insert(0,chr);
            
            counter2++;
            }
String str= temp2.toString().trim();
         String res1 = res.concat(str);
       
            
        int bin3 = Integer.parseInt(dataa3);
        String xyy= Integer.toBinaryString(bin3);
         StringBuffer temp3 = new StringBuffer(xyy);    
        int counter3 =temp3.length();
            while(counter3<4){
            char chr ='0';
            temp3.insert(0,chr);
            
            counter3++;
            }
            String str2= temp3.toString().trim();
            String res2 =res1.concat(str2) ;
        String finres =res2.toString().trim();
        genbintxt6.setText(finres);
    }
            // third text box value read
            
            String line3 = genbin3.getText();{
           String[] tokens = line3.split(",(?=([^\"]*\"[^\"]*\")*[^\"]*$)");
               String dataa1 =(tokens[0].toString().trim());
           String dataa2 = (tokens[1].toString().trim());
           String dataa3 = (tokens[2].toString().trim());
           int binry = Integer.parseInt(dataa1);
        String xyz= Integer.toBinaryString(binry);
        StringBuffer temp1 = new StringBuffer(xyz);
  
            int counter =temp1.length();
            while(counter<4){
            char chr ='0';
            temp1.insert(0,chr);
            
            counter++;
            }
            String res=  temp1.toString().trim();
           int binr = Integer.parseInt(dataa2);         
        String xy= Integer.toBinaryString(binr);
        StringBuffer temp2 = new StringBuffer(xy);    
        int counter2 =temp2.length();
            while(counter2<4){
            char chr ='0';
            temp2.insert(0,chr);
            
            counter2++;
            }
String str= temp2.toString().trim();
         String res1 = res.concat(str);
       
            
        int bin3 = Integer.parseInt(dataa3);
        String xyy= Integer.toBinaryString(bin3);
         StringBuffer temp3 = new StringBuffer(xyy);    
        int counter3 =temp3.length();
            while(counter3<4){
            char chr ='0';
            temp3.insert(0,chr);
            
            counter3++;
            }
            String str2= temp3.toString().trim();
            String res2 =res1.concat(str2) ;
        String finres =res2.toString().trim();
        genbintxt7.setText(finres);
    }
            String line4 = genbin4.getText();{
           String[] tokens = line4.split(",(?=([^\"]*\"[^\"]*\")*[^\"]*$)");
               String dataa1 =(tokens[0].toString().trim());
           String dataa2 = (tokens[1].toString().trim());
           String dataa3 = (tokens[2].toString().trim());
           int binry = Integer.parseInt(dataa1);
        String xyz= Integer.toBinaryString(binry);
        StringBuffer temp1 = new StringBuffer(xyz);
  
            int counter =temp1.length();
            while(counter<4){
            char chr ='0';
            temp1.insert(0,chr);
            
            counter++;
            }
            String res=  temp1.toString().trim();
           int binr = Integer.parseInt(dataa2);         
        String xy= Integer.toBinaryString(binr);
        StringBuffer temp2 = new StringBuffer(xy);    
        int counter2 =temp2.length();
            while(counter2<4){
            char chr ='0';
            temp2.insert(0,chr);
            
            counter2++;
            }
String str= temp2.toString().trim();
         String res1 = res.concat(str);
       
            
        int bin3 = Integer.parseInt(dataa3);
        String xyy= Integer.toBinaryString(bin3);
         StringBuffer temp3 = new StringBuffer(xyy);    
        int counter3 =temp3.length();
            while(counter3<4){
            char chr ='0';
            temp3.insert(0,chr);
            
            counter3++;
            }
            String str2= temp3.toString().trim();
            String res2 =res1.concat(str2) ;
        String finres =res2.toString().trim();
        genbintxt8.setText(finres);
    }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:\
        String str = genbintxt5.getText();
        String substr1 = str.substring(0, 6);
        String substr2 =str.substring(6);
        binsptxt1.setText(substr1);
        binsptxt5.setText(substr2);
        //2nd txt
        String str6 = genbintxt6.getText();
        String substr61 = str6.substring(0, 6);
        String substr62 =str6.substring(6);
        binsptxt2.setText(substr61);
        binsptxt6.setText(substr62);
        
        // 3rd txt
        String str7 = genbintxt7.getText();
        String substr71 = str7.substring(0, 6);
        String substr72 =str7.substring(6);
        binsptxt3.setText(substr71);
        binsptxt7.setText(substr72);
        //4th txt
        String str8 = genbintxt8.getText();
        String substr81 = str8.substring(0, 6);
        String substr82 =str8.substring(6);
        binsptxt4.setText(substr81);
        binsptxt8.setText(substr82);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String tr1 = binsptxt1.getText();
        String tr6 = binsptxt6.getText();
        String res1 = tr1.concat(tr6);
        crrtxt1.setText(res1);
        // 2nd res
        String tr2 = binsptxt2.getText();
        String tr5 = binsptxt5.getText();
        String res2 = tr2.concat(tr5);
        crrtxt2.setText(res2);
        //3rd res
        String tr3 = binsptxt3.getText();
        String tr8 = binsptxt8.getText();
        String res3 = tr3.concat(tr8);
        crrtxt3.setText(res3);
        //4th res 
        String tr4 = binsptxt4.getText();
        String tr7 = binsptxt7.getText();
        String res4 = tr4.concat(tr7);
        crrtxt4.setText(res4);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        imagealgo imal = new imagealgo();
        imal.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                 String abc  =crrtxt1.getText();
        //abc.replace("1", "0");
        String nstt;
        String stt = abc.substring(0,1);
        String ressub = abc.substring(1);
        
        if(stt.equals("0")){
         nstt= stt.replace("0", "1");
         }
        else {
            nstt= stt.replace("1", "0");
        }
        String res1 =nstt.concat(ressub);
        muttxt1.setText(res1);
        
        //2nd txt box
        String abc2  =crrtxt2.getText();
        //abc.replace("1", "0");
        String nstt2;
        String stt2 = abc2.substring(0,1);
        String ressub2 = abc2.substring(1);
        
        if(stt2.equals("0")){
         nstt2= stt2.replace("0", "1");
         }
        else {
            nstt2= stt2.replace("1", "0");
        }
        String res2 =nstt2.concat(ressub2);
        muttxt2.setText(res2);
        //3rd texxt
         String abc3  =crrtxt3.getText();
        //abc.replace("1", "0");
        String nstt3;
        String stt3 = abc3.substring(0,1);
        String ressub3 = abc3.substring(1);
        
        if(stt3.equals("0")){
         nstt3= stt3.replace("0", "1");
         }
        else {
            nstt3= stt3.replace("1", "0");
        }
        String res3 =nstt3.concat(ressub2);
        muttxt3.setText(res3);
        //4th
         String abc4  =crrtxt4.getText();
        //abc.replace("1", "0");
        String nstt4;
        String stt4 = abc4.substring(0,1);
        String ressub4 = abc4.substring(1);
        
        if(stt4.equals("0")){
         nstt4= stt4.replace("0", "1");
         }
        else {
            nstt4= stt4.replace("1", "0");
        }
        String res4 =nstt4.concat(ressub4);
        muttxt4.setText(res4);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
               String str1 =muttxt1.getText();
        String num1 =str1.substring(0,4);
        String num2 =str1.substring(4,8);
        String num3 =str1.substring(8,12);
         String numb = String.valueOf(num1.trim());
                 int decimalNumber = Integer.parseInt(numb,2);
                 String decval1 = String.valueOf(decimalNumber);
                  numb = String.valueOf(num2.trim());
                  decimalNumber = Integer.parseInt(numb,2);
                 String decval2 = String.valueOf(decimalNumber);
                  numb = String.valueOf(num3.trim());
                  decimalNumber = Integer.parseInt(numb,2);
                 String decval3 = String.valueOf(decimalNumber);
                 String restemp = decval1+","+decval2+","+decval3;
                 dectxt1.setText(restemp);
                 
                 //2nd text
                    String str2 =muttxt2.getText();
        String num12 =str2.substring(0,4);
        String num22 =str2.substring(4,8);
        String num32 =str2.substring(8,12);
         String numb2 = String.valueOf(num12.trim());
                 int decimalNumber2 = Integer.parseInt(numb2,2);
                 String decval12 = String.valueOf(decimalNumber2);
                  numb2 = String.valueOf(num22.trim());
                  decimalNumber2 = Integer.parseInt(numb2,2);
                 String decval22 = String.valueOf(decimalNumber2);
                  numb2 = String.valueOf(num32.trim());
                  decimalNumber2 = Integer.parseInt(numb2,2);
                 String decval32 = String.valueOf(decimalNumber2);
                 String restemp2 = decval12+","+decval22+","+decval32;
                 dectxt2.setText(restemp2);
                //3rd text
                    String str3 =muttxt3.getText();
        String num13 =str3.substring(0,4);
        String num23 =str3.substring(4,8);
        String num33=str3.substring(8,12);
         String numb3 = String.valueOf(num13.trim());
                 int decimalNumber3 = Integer.parseInt(numb3,2);
                 String decval13 = String.valueOf(decimalNumber3);
                  numb3 = String.valueOf(num23.trim());
                  decimalNumber3 = Integer.parseInt(numb3,2);
                 String decval23 = String.valueOf(decimalNumber3);
                  numb3 = String.valueOf(num33.trim());
                  decimalNumber3 = Integer.parseInt(numb3,2);
                 String decval33 = String.valueOf(decimalNumber3);
                 String restemp3 = decval13+","+decval23+","+decval33;
                 dectxt3.setText(restemp3);
                 //4th txt
                    String str4 =muttxt4.getText();
        String num14 =str4.substring(0,4);
        String num24 =str4.substring(4,8);
        String num34 =str4.substring(8,12);
         String numb4 = String.valueOf(num14.trim());
                 int decimalNumber4= Integer.parseInt(numb4,2);
                 String decval14 = String.valueOf(decimalNumber4);
                  numb4 = String.valueOf(num24.trim());
                  decimalNumber4= Integer.parseInt(numb4,2);
                 String decval24 = String.valueOf(decimalNumber4);
                  numb4 = String.valueOf(num34.trim());
                  decimalNumber4 = Integer.parseInt(numb4,2);
                 String decval34 = String.valueOf(decimalNumber4);
                 String restemp4 = decval14+","+decval24+","+decval34;
                 dectxt4.setText(restemp4);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frame4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField binsptxt1;
    private javax.swing.JTextField binsptxt2;
    private javax.swing.JTextField binsptxt3;
    private javax.swing.JTextField binsptxt4;
    private javax.swing.JTextField binsptxt5;
    private javax.swing.JTextField binsptxt6;
    private javax.swing.JTextField binsptxt7;
    private javax.swing.JTextField binsptxt8;
    private javax.swing.JTextField crrtxt1;
    private javax.swing.JTextField crrtxt2;
    private javax.swing.JTextField crrtxt3;
    private javax.swing.JTextField crrtxt4;
    private javax.swing.JTextField data1;
    private javax.swing.JTextField data2;
    private javax.swing.JTextField data3;
    private javax.swing.JTextField data4;
    private javax.swing.JTextField dectxt1;
    private javax.swing.JTextField dectxt2;
    private javax.swing.JTextField dectxt3;
    private javax.swing.JTextField dectxt4;
    private javax.swing.JTextField fvtxt1;
    private javax.swing.JTextField fvtxt2;
    private javax.swing.JTextField fvtxt3;
    private javax.swing.JTextField fvtxt4;
    private javax.swing.JTextField genbin1;
    private javax.swing.JTextField genbin2;
    private javax.swing.JTextField genbin3;
    private javax.swing.JTextField genbin4;
    private javax.swing.JTextField genbintxt5;
    private javax.swing.JTextField genbintxt6;
    private javax.swing.JTextField genbintxt7;
    private javax.swing.JTextField genbintxt8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField muttxt1;
    private javax.swing.JTextField muttxt2;
    private javax.swing.JTextField muttxt3;
    private javax.swing.JTextField muttxt4;
    private javax.swing.JTextField pathtxt1;
    private javax.swing.JTextField pathtxt2;
    private javax.swing.JTextField pathtxt3;
    private javax.swing.JTextField pathtxt4;
    private javax.swing.JTextField prttxt1;
    private javax.swing.JTextField prttxt2;
    private javax.swing.JTextField prttxt3;
    private javax.swing.JTextField prttxt4;
    // End of variables declaration//GEN-END:variables
}
